### ISSUE TITLE
Update Buildkite job to build release binaries on `master-nearcore` branch for Indexer Framework-based version of indexer

### ISSUE THREAD

**Issue by khorolets** [near/near-indexer-for-explorer#332]
Since #326 is merged Buildkite is not useful for the `master` branch. We need to update the Buildkite job to be working only on `master-nearcore` branch while we are running both versions of Indexer for Explorer (Indexer Framework-based aka nearcore and Lake-based)

After we shut down the last `nearcore`-based node we will disable the Buildkite from this repository completely.

**Comment by ecp88** [comment]
This has been resolved. Build kite has been updated.

**Comment by khorolets** [comment]
Reopening since we still see the Buildkite jobs in PRs against `master` branch. Please, fix it :)
